[package]
name = "proxy"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.0", features = ["derive"] }
dns-lookup = "2.0.4"
pnet_transport = "0.34.0"
lazy_static = "1.4.0"

[dependencies.pnet]
version = "0.34.0"